-- =====================================================================================
-- BOP KUA Kabupaten Indramayu: SKEMA DATABASE LENGKAP (satu file)
--
-- Cara pakai: Supabase > SQL Editor > New query > tempel seluruh isi file ini > Run.
-- Aman dijalankan berulang (idempotent). Cocok untuk:
--   (a) pemasangan baru (database kosong);
--   (b) database versi lama: RPD/Realisasi per-POS dikonversi otomatis menjadi 1 record per bulan (JSON),
--       lalu tabel lama (rpd_lama, realisasi_lama) dihapus setelah dipastikan datanya sudah pindah.
--
-- Isi: 0 Persiapan | 1 Profil dan hak akses | 2 KUA | 3 Fungsi bantu | 4 POS | 5 Config | 6 Anggaran |
--      7 AutoPayment (arsip) | 8 RPD | 9 Realisasi | 9b Pembayaran SAKTI | 10 Salin data lama | 11 Pembersihan
--
-- Model data: RPD dan Realisasi = 1 record per KUA per bulan; rincian POS disimpan di kolom JSON
--   items = {"<id POS>": nominal, ...}. Total dihitung otomatis oleh trigger. Pembayaran SAKTI (Listrik, Telepon/Internet, Air)
--   memakai tabel metode_pembayaran (metode per KUA + POS) dan realisasi_sakti (diinput admin per bulan); keduanya dijumlahkan
--   dengan Realisasi manual pada validasi dan laporan. Tabel autopayment_pos (nominal tetap) kini arsip: sudah dimigrasikan sekali.
-- Keamanan: RLS membatasi operator ke KUA-nya; trigger SECURITY DEFINER menegakkan semua aturan di sisi server.
-- =====================================================================================

-- 0) PERSIAPAN: bila masih struktur lama (RPD/Realisasi per-POS), pindahkan dulu menjadi *_lama
do $$ begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'rpd' and column_name = 'pos_id') then
    drop trigger if exists rpd_guard on public.rpd;
    alter table public.rpd rename to rpd_lama;
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'realisasi' and column_name = 'pos_id') then
    drop trigger if exists realisasi_a_lock on public.realisasi;
    drop trigger if exists realisasi_guard on public.realisasi;
    alter table public.realisasi rename to realisasi_lama;
  end if;
end $$;

-- 1) PROFIL AKUN DAN HAK AKSES -----------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nama text not null,
  kua text,
  role text not null default 'operator' check (role in ('admin','operator')),
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

create or replace function public.is_admin() returns boolean
language sql security definer stable set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

-- operator hanya melihat profilnya sendiri, admin melihat semua. Tanpa policy insert/update/delete: klien tidak bisa mengubah role.
drop policy if exists "baca profil sendiri atau admin" on public.profiles;
create policy "baca profil sendiri atau admin" on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.is_admin());

-- profil dibuat otomatis saat akun dibuat (data dari user_metadata); kua_id dicari dari nama KUA
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, nama, kua, kua_id, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'nama', new.email), new.raw_user_meta_data->>'kua',
    (select id from public.kua where nama_kua = new.raw_user_meta_data->>'kua'),
    case when new.raw_user_meta_data->>'role' = 'admin' then 'admin' else 'operator' end);
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- 2) KUA (31 kecamatan) ------------------------------------------------------------------
create table if not exists public.kua (
  id int generated by default as identity primary key,
  nama_kua text not null unique,
  kecamatan text not null,
  status text not null default 'aktif' check (status in ('aktif','nonaktif'))
);
insert into public.kua (nama_kua, kecamatan)
select 'KUA Kec. ' || k, k from unnest(array['Anjatan','Arahan','Balongan','Bangodua','Bongas','Cantigi','Cikedung',
  'Gabuswetan','Gantar','Haurgeulis','Indramayu','Jatibarang','Juntinyuat','Kandanghaur','Karangampel','Kedokan Bunder',
  'Kertasemaya','Krangkeng','Kroya','Lelea','Lohbener','Losarang','Pasekan','Patrol','Sindang','Sliyeg','Sukagumiwang',
  'Sukra','Terisi','Tukdana','Widasari']) as k
on conflict (nama_kua) do nothing;
alter table public.profiles add column if not exists kua_id int references public.kua(id);
update public.profiles p set kua_id = k.id from public.kua k where p.kua_id is null and p.kua = k.nama_kua;

create or replace function public.my_kua() returns int
language sql security definer stable set search_path = public as $$
  select kua_id from public.profiles where id = auth.uid();
$$;

alter table public.kua enable row level security;
drop policy if exists kua_read on public.kua;
create policy kua_read on public.kua for select to authenticated using (true);

-- 3) FUNGSI BANTU ------------------------------------------------------------------------
create or replace function public.rp(n bigint) returns text
language sql stable as $$ select 'Rp ' || replace(to_char(n, 'FM999,999,999,999,999'), ',', '.'); $$;

create or replace function public.nama_bulan(m int) returns text language sql immutable as $$
  select (array['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'])[m];
$$;

create or replace function public.items_total(p jsonb) returns bigint
language sql immutable as $$ select coalesce(sum(value::bigint), 0)::bigint from jsonb_each_text(p); $$;

-- 4) POS: satu baris = satu unit input (rincian, atau kode POS itu sendiri bila tanpa rincian) -------------
create table if not exists public.pos (
  id int generated by default as identity primary key,
  kode_pos text not null,
  nama_pos text not null,
  nama_rincian text,
  urutan int not null unique
);
insert into public.pos (kode_pos, nama_pos, nama_rincian, urutan) values
 ('521111','Belanja Operasional Perkantoran','ATK Kantor',1),
 ('521111','Belanja Operasional Perkantoran','Jamuan Tamu',2),
 ('521111','Belanja Operasional Perkantoran','Pramubakti',3),
 ('521111','Belanja Operasional Perkantoran','Alat Rumah Tangga Kantor',4),
 ('521211','Belanja Bahan','Penggandaan / Penjilidan',5),
 ('521211','Belanja Bahan','Spanduk',6),
 ('522111','Belanja Langganan Listrik',null,7),
 ('522112','Belanja Langganan Telepon / Internet',null,8),
 ('522113','Belanja Langganan Air',null,9),
 ('523111','Belanja Pemeliharaan Gedung dan Bangunan',null,10),
 ('523121','Belanja Pemeliharaan Peralatan dan Mesin',null,11)
on conflict (urutan) do nothing;

create or replace function public.pos_label(p_id int) returns text
language sql stable set search_path = public as $$
  select kode_pos || ' ' || coalesce(nama_rincian, nama_pos) from pos where id = p_id;
$$;

-- Rapikan dan validasi rincian: kunci = id POS yang ada, nilai = bilangan bulat >= 0; nilai 0 dibuang
create or replace function public.norm_items(p jsonb) returns jsonb
language plpgsql stable set search_path = public as $$
declare k text; v jsonb; r jsonb := '{}'::jsonb;
begin
  if p is null or jsonb_typeof(p) <> 'object' then raise exception 'Format rincian POS tidak valid.'; end if;
  for k, v in select key, value from jsonb_each(p) loop
    if jsonb_typeof(v) <> 'number' or (v #>> '{}') !~ '^[0-9]+$' then
      raise exception 'Nominal POS % harus bilangan bulat dan tidak negatif.', k; end if;
    if not exists (select 1 from pos where id::text = k) then raise exception 'POS % tidak dikenal.', k; end if;
    if (v #>> '{}')::bigint > 0 then r := r || jsonb_build_object(k, (v #>> '{}')::bigint); end if;
  end loop;
  return r;
end $$;

alter table public.pos enable row level security;
drop policy if exists pos_read on public.pos;
create policy pos_read on public.pos for select to authenticated using (true);

-- 5) CONFIG global ---------------------------------------------------------------------------
create table if not exists public.config (
  key text primary key, value jsonb not null,
  updated_by uuid references auth.users(id), updated_at timestamptz not null default now()
);
insert into public.config (key, value) values
 ('wajib_lpj','true'),('rpd_enabled','true'),('realisasi_enabled','true'),
 ('max_file_size_mb','5'),('max_file_count','3'),('bulan_edit_rpd','[1,2,3,4,5,6,7,8,9,10,11,12]')
on conflict (key) do nothing;

-- Operator boleh edit RPD hanya jika rpd_enabled dan bulan ada di bulan_edit_rpd
create or replace function public.rpd_open(m int) returns boolean
language sql security definer stable set search_path = public as $$
  select coalesce((select (value #>> '{}')::boolean from config where key = 'rpd_enabled'), false)
     and exists (select 1 from config where key = 'bulan_edit_rpd' and value @> to_jsonb(m));
$$;

alter table public.config enable row level security;
drop policy if exists cfg_read on public.config;
create policy cfg_read on public.config for select to authenticated using (true);
drop policy if exists cfg_admin on public.config;
create policy cfg_admin on public.config for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- 6) ANGGARAN TAHUNAN ------------------------------------------------------------------------
create table if not exists public.anggaran (
  id bigint generated by default as identity primary key,
  kua_id int not null references public.kua(id),
  tahun int not null check (tahun between 2020 and 2100),
  nominal_total bigint not null check (nominal_total >= 0),
  updated_by uuid references auth.users(id), updated_at timestamptz not null default now(),
  unique (kua_id, tahun)
);

-- Anggaran tidak boleh diturunkan di bawah total RPD yang sudah diisi (pesan menyebut nama KUA)
create or replace function public.anggaran_guard() returns trigger
language plpgsql security definer set search_path = public as $$
declare used bigint;
begin
  perform pg_advisory_xact_lock(new.kua_id, new.tahun);
  select coalesce(sum(total), 0) into used from rpd where kua_id = new.kua_id and tahun = new.tahun;
  if new.nominal_total < used then
    raise exception '%: Anggaran % lebih kecil dari total RPD yang sudah diisi (%). Kurangi RPD lebih dulu.',
      (select nama_kua from kua where id = new.kua_id), rp(new.nominal_total), rp(used);
  end if;
  new.updated_by := auth.uid(); new.updated_at := now();
  return new;
end $$;
drop trigger if exists anggaran_guard on public.anggaran;
create trigger anggaran_guard before insert or update on public.anggaran
  for each row execute function public.anggaran_guard();

alter table public.anggaran enable row level security;
drop policy if exists ang_read on public.anggaran;
create policy ang_read on public.anggaran for select to authenticated using (public.is_admin() or kua_id = public.my_kua());
drop policy if exists ang_admin on public.anggaran;
create policy ang_admin on public.anggaran for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- 7) AUTOPAYMENT LAMA (ARSIP; digantikan bagian 9b. Tidak dipakai lagi oleh validasi, dimigrasikan sekali ke SAKTI) -----------
-- Versi konfigurasi: (mulai, sampai) agar riwayat bulan lampau tidak berubah ketika nominal diganti.
create table if not exists public.autopayment_pos (
  kua_id int not null references public.kua(id) on delete cascade,
  pos_id int not null references public.pos(id) on delete cascade,
  nominal bigint not null default 0 check (nominal >= 0),
  mulai date not null default date_trunc('month', now() at time zone 'Asia/Jakarta')::date,
  sampai date,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  primary key (kua_id, pos_id, mulai)
);
-- (database lama: lengkapi kolom dan kunci utama)
alter table public.autopayment_pos add column if not exists nominal bigint not null default 0 check (nominal >= 0);
alter table public.autopayment_pos add column if not exists mulai date not null default date_trunc('month', now() at time zone 'Asia/Jakarta')::date;
alter table public.autopayment_pos add column if not exists sampai date;
do $$ begin
  if (select array_length(conkey, 1) from pg_constraint where conrelid = 'public.autopayment_pos'::regclass and contype = 'p') = 2 then
    alter table public.autopayment_pos drop constraint autopayment_pos_pkey;
    alter table public.autopayment_pos add primary key (kua_id, pos_id, mulai);
  end if;
end $$;

create or replace function public.autopayment_pos_guard() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from pos where id = new.pos_id and kode_pos in ('522111','522112','522113')) then
    raise exception 'AutoPayment hanya untuk Listrik, Telepon/Internet, dan Air.'; end if;
  return new;
end $$;
drop trigger if exists autopayment_pos_guard on public.autopayment_pos;
create trigger autopayment_pos_guard before insert or update on public.autopayment_pos
  for each row execute function public.autopayment_pos_guard();

-- AutoPayment virtual: nominal tetap selama versi konfigurasi berlaku, sampai bulan berjalan (WIB)
create or replace function public.auto_items(p_kua int, p_tahun int, p_bulan int) returns jsonb
language sql stable set search_path = public as $$
  select coalesce(jsonb_object_agg(pos_id::text, nominal), '{}'::jsonb) from autopayment_pos
   where kua_id = p_kua and nominal > 0
     and make_date(p_tahun, p_bulan, 1) <= date_trunc('month', now() at time zone 'Asia/Jakarta')::date
     and make_date(p_tahun, p_bulan, 1) >= mulai
     and (sampai is null or make_date(p_tahun, p_bulan, 1) <= sampai);
$$;

create or replace function public.auto_year(p_kua int, p_pos int, p_tahun int) returns bigint
language sql stable set search_path = public as $$
  select coalesce(sum(a.nominal), 0)::bigint from autopayment_pos a, generate_series(1, 12) m
   where a.kua_id = p_kua and a.pos_id = p_pos and a.nominal > 0
     and make_date(p_tahun, m, 1) <= date_trunc('month', now() at time zone 'Asia/Jakarta')::date
     and make_date(p_tahun, m, 1) >= a.mulai and (a.sampai is null or make_date(p_tahun, m, 1) <= a.sampai);
$$;

-- Atur AutoPayment sekaligus: [{"kua_id":1,"pos_id":7,"nominal":300000}, ...]; nominal 0 = nonaktifkan. Berlaku mulai bulan ini.
create or replace function public.set_autopayment(p_items jsonb) returns void
language plpgsql security definer set search_path = public as $$
declare it jsonb; a record; n bigint; cur date := date_trunc('month', now() at time zone 'Asia/Jakarta')::date;
begin
  if not public.is_admin() then raise exception 'Hanya admin yang dapat mengatur AutoPayment.'; end if;
  for it in select value from jsonb_array_elements(p_items) loop
    n := coalesce((it ->> 'nominal')::bigint, 0);
    select * into a from autopayment_pos where kua_id = (it ->> 'kua_id')::int and pos_id = (it ->> 'pos_id')::int and sampai is null;
    if n > 0 then
      if found then
        if a.nominal = n then continue; end if;
        if a.mulai >= cur then
          update autopayment_pos set nominal = n where kua_id = a.kua_id and pos_id = a.pos_id and mulai = a.mulai;
        else
          update autopayment_pos set sampai = (cur - interval '1 month')::date where kua_id = a.kua_id and pos_id = a.pos_id and mulai = a.mulai;
          insert into autopayment_pos (kua_id, pos_id, nominal, mulai) values (a.kua_id, a.pos_id, n, cur);
        end if;
      else
        insert into autopayment_pos (kua_id, pos_id, nominal, mulai) values ((it ->> 'kua_id')::int, (it ->> 'pos_id')::int, n, cur);
      end if;
    elsif found then
      if a.mulai >= cur then
        delete from autopayment_pos where kua_id = a.kua_id and pos_id = a.pos_id and mulai = a.mulai;
      else
        update autopayment_pos set sampai = (cur - interval '1 month')::date where kua_id = a.kua_id and pos_id = a.pos_id and mulai = a.mulai;
      end if;
    end if;
  end loop;
end $$;
revoke execute on function public.set_autopayment(jsonb) from public, anon;
grant execute on function public.set_autopayment(jsonb) to authenticated;

alter table public.autopayment_pos enable row level security;
drop policy if exists ap_admin on public.autopayment_pos;
create policy ap_admin on public.autopayment_pos for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
drop policy if exists ap_read on public.autopayment_pos;
create policy ap_read on public.autopayment_pos for select to authenticated using (kua_id = public.my_kua());

-- 8) RPD: 1 record = 1 KUA x 1 bulan -----------------------------------------------------------
create table if not exists public.rpd (
  id bigint generated by default as identity primary key,
  kua_id int not null references public.kua(id),
  tahun int not null check (tahun between 2020 and 2100),
  bulan int not null check (bulan between 1 and 12),
  items jsonb not null default '{}'::jsonb check (jsonb_typeof(items) = 'object'),
  total bigint not null default 0 check (total >= 0),
  updated_by uuid references auth.users(id), updated_at timestamptz not null default now(),
  unique (kua_id, tahun, bulan)
);

-- Total RPD setahun <= Anggaran Tahunan; operator hanya boleh menyentuh KUA-nya sendiri
create or replace function public.rpd_guard() returns trigger
language plpgsql security definer set search_path = public as $$
declare cap bigint; used bigint;
begin
  if not public.is_admin() and public.my_kua() is distinct from new.kua_id then
    raise exception 'Anda tidak berhak mengubah data KUA lain.'; end if;
  new.items := norm_items(new.items); new.total := items_total(new.items);
  perform pg_advisory_xact_lock(new.kua_id, new.tahun);
  select nominal_total into cap from anggaran where kua_id = new.kua_id and tahun = new.tahun;
  if cap is null then raise exception 'Anggaran Tahunan % belum ditetapkan admin untuk KUA ini.', new.tahun; end if;
  select coalesce(sum(total), 0) into used from rpd where kua_id = new.kua_id and tahun = new.tahun and bulan <> new.bulan;
  if used + new.total > cap then
    raise exception 'Total RPD melebihi Anggaran Tahunan. Batas: %, sudah terpakai (bulan lain): %, dimasukkan: %, kelebihan: %.',
      rp(cap), rp(used), rp(new.total), rp(used + new.total - cap);
  end if;
  new.updated_by := auth.uid(); new.updated_at := now();
  return new;
end $$;
drop trigger if exists rpd_guard on public.rpd;
create trigger rpd_guard before insert or update on public.rpd for each row execute function public.rpd_guard();

alter table public.rpd enable row level security;
drop policy if exists rpd_read on public.rpd;
create policy rpd_read on public.rpd for select to authenticated using (public.is_admin() or kua_id = public.my_kua());
drop policy if exists rpd_write on public.rpd;
create policy rpd_write on public.rpd for all to authenticated
  using (public.is_admin() or (kua_id = public.my_kua() and public.rpd_open(bulan)))
  with check (public.is_admin() or (kua_id = public.my_kua() and public.rpd_open(bulan)));

-- 9) REALISASI: 1 record = 1 KUA x 1 bulan ------------------------------------------------------
create table if not exists public.realisasi (
  id bigint generated by default as identity primary key,
  kua_id int not null references public.kua(id),
  tahun int not null check (tahun between 2020 and 2100),
  bulan int not null check (bulan between 1 and 12),
  items jsonb not null default '{}'::jsonb check (jsonb_typeof(items) = 'object'),
  total bigint not null default 0 check (total >= 0),
  status text not null default 'waiting' check (status in ('waiting','approved','rejected','paid')),
  file_lpj_url text check (file_lpj_url is null or file_lpj_url ~ '^https://(drive|docs)\.google\.com/'),
  catatan_admin text,
  submitted_by uuid references auth.users(id), submitted_at timestamptz,
  verified_by uuid references auth.users(id), verified_at timestamptz,
  paid_at timestamptz,
  unique (kua_id, tahun, bulan)
);
create index if not exists realisasi_filter on public.realisasi (tahun, status, kua_id);

-- Operator: hanya boleh membuat (belum ada) atau memperbaiki yang berstatus rejected; setelah dikirim jadi waiting dan terkunci.
-- Admin: boleh mengubah status apa pun kapan pun, tetapi TIDAK boleh mengubah nominal / dokumen LPJ.
create or replace function public.realisasi_guard() returns trigger
language plpgsql security definer set search_path = public as $$
declare sk jsonb; rpd_m bigint; sk_m bigint; ctx text; k text; v bigint; cap bigint; used bigint;
begin
  if tg_op = 'UPDATE' and public.is_admin() then
    if (new.kua_id, new.tahun, new.bulan, new.items, new.total, new.file_lpj_url)
       is distinct from (old.kua_id, old.tahun, old.bulan, old.items, old.total, old.file_lpj_url) then
      raise exception 'Admin hanya dapat mengubah status dan catatan, bukan nominal atau dokumen LPJ.'; end if;
    if new.status = 'rejected' and btrim(coalesce(new.catatan_admin, '')) = '' then
      raise exception 'Alasan penolakan wajib diisi.'; end if;
    if new.status <> old.status then
      new.verified_by := auth.uid(); new.verified_at := now();
      new.paid_at := case when new.status = 'paid' then now() end;
    end if;
    return new;
  end if;

  if public.my_kua() is distinct from new.kua_id then
    raise exception 'Anda tidak berhak mengubah data KUA lain.'; end if;
  if tg_op = 'UPDATE' then
    if old.status <> 'rejected' then
      raise exception 'Realisasi berstatus % tidak dapat diubah. Hanya Realisasi yang ditolak yang dapat diperbaiki.',
        case old.status when 'waiting' then 'Menunggu verifikasi' when 'approved' then 'Disetujui' else 'Dibayar' end; end if;
    if (new.kua_id, new.tahun, new.bulan) is distinct from (old.kua_id, old.tahun, old.bulan) then
      raise exception 'KUA, tahun, dan bulan tidak dapat diubah.'; end if;
    new.catatan_admin := old.catatan_admin; new.verified_by := old.verified_by; new.verified_at := old.verified_at;
  else
    new.catatan_admin := null; new.verified_by := null; new.verified_at := null;
  end if;
  new.paid_at := null; new.status := 'waiting'; new.submitted_by := auth.uid(); new.submitted_at := now();
  new.items := norm_items(new.items); new.total := items_total(new.items);

  if coalesce((select (value #>> '{}')::boolean from config where key = 'realisasi_enabled'), false) is not true then
    raise exception 'Pengisian Realisasi sedang ditutup oleh admin.'; end if;
  if (now() at time zone 'Asia/Jakarta')::date < make_date(new.tahun, new.bulan, 10) then
    raise exception 'Realisasi % % baru dapat disubmit mulai tanggal 10 %.', nama_bulan(new.bulan), new.tahun, nama_bulan(new.bulan); end if;
  if new.total > 0 and new.file_lpj_url is null then
    raise exception 'LPJ wajib dilampirkan (unggah file LPJ).'; end if;

  select nama_kua into ctx from kua where id = new.kua_id;
  perform pg_advisory_xact_lock(new.kua_id, new.tahun);
  -- POS bermetode SAKTI pada bulan itu hanya diinput admin (tabel realisasi_sakti), tidak boleh diisi operator
  for k in select jsonb_object_keys(new.items) loop
    if metode_pos(new.kua_id, k::int, new.tahun, new.bulan) = 'SAKTI' then
      raise exception '%: POS % bermetode SAKTI pada % %. Realisasinya diinput oleh Admin dan tidak dapat diisi manual.',
        ctx, pos_label(k::int), nama_bulan(new.bulan), new.tahun; end if;
  end loop;
  sk := sakti_items(new.kua_id, new.tahun, new.bulan);

  select coalesce(sum(total), 0) into rpd_m from rpd where kua_id = new.kua_id and tahun = new.tahun and bulan = new.bulan;
  sk_m := items_total(sk);
  if new.total + sk_m > rpd_m then
    raise exception '%: total Realisasi bulan ini melebihi RPD bulan ini. Batas: %, SAKTI: %, dimasukkan: %, kelebihan: %.',
      ctx, rp(rpd_m), rp(sk_m), rp(new.total), rp(new.total + sk_m - rpd_m); end if;

  for k, v in select key, value::bigint from jsonb_each_text(new.items) loop
    select coalesce(sum((items ->> k)::bigint), 0) into cap from rpd where kua_id = new.kua_id and tahun = new.tahun;
    select coalesce(sum((items ->> k)::bigint), 0) + sakti_year(new.kua_id, k::int, new.tahun) into used
      from realisasi where kua_id = new.kua_id and tahun = new.tahun and bulan <> new.bulan;
    if used + v > cap then
      raise exception '%: Realisasi POS % melebihi total RPD setahun. Batas: %, terpakai (bulan lain + SAKTI): %, dimasukkan: %, kelebihan: %.',
        ctx, pos_label(k::int), rp(cap), rp(used), rp(v), rp(used + v - cap); end if;
  end loop;
  return new;
end $$;
drop trigger if exists realisasi_guard on public.realisasi;
create trigger realisasi_guard before insert or update on public.realisasi
  for each row execute function public.realisasi_guard();

-- aturan status dijaga trigger realisasi_guard agar pesan errornya jelas
alter table public.realisasi enable row level security;
drop policy if exists rl_read on public.realisasi;
create policy rl_read on public.realisasi for select to authenticated using (public.is_admin() or kua_id = public.my_kua());
drop policy if exists rl_ins on public.realisasi;
create policy rl_ins on public.realisasi for insert to authenticated with check (kua_id = public.my_kua());
drop policy if exists rl_upd on public.realisasi;
create policy rl_upd on public.realisasi for update to authenticated
  using (public.is_admin() or kua_id = public.my_kua())
  with check (public.is_admin() or kua_id = public.my_kua());

-- 9b) PEMBAYARAN SAKTI --------------------------------------------------------------------------------------
-- Tiap KUA + POS punya metode pembayaran: MANUAL (operator mengisi Realisasi) atau SAKTI (admin menginput Realisasi SAKTI;
-- operator tidak bisa mengisinya). Hanya Listrik 522111, Telepon/Internet 522112, dan Air 522113 yang dapat memakai SAKTI.
-- KUA + POS yang belum diatur = MANUAL (perilaku lama tidak berubah).
-- Konfigurasi berversi per bulan berlaku (mulai): metode suatu bulan = versi terbaru dengan mulai <= bulan itu. Mengganti
-- metode hanya mengubah bulan sejak berlaku; Realisasi bulan sebelumnya (manual maupun SAKTI) tidak disentuh.
-- Realisasi SAKTI disimpan terpisah (realisasi_sakti, 1 baris = KUA x POS x bulan) dan dijumlahkan dengan Realisasi manual
-- pada semua validasi dan laporan. Tidak ada DELETE untuk siapa pun (data keuangan): koreksi dengan UPDATE.

create table if not exists public.metode_pembayaran (
  kua_id int not null references public.kua(id),
  pos_id int not null references public.pos(id),
  metode text not null check (metode in ('MANUAL','SAKTI')),
  mulai date not null check (extract(day from mulai) = 1 and mulai between date '2020-01-01' and date '2100-12-01'),
  created_by uuid references auth.users(id), created_at timestamptz not null default now(),
  updated_by uuid references auth.users(id), updated_at timestamptz not null default now(),
  primary key (kua_id, pos_id, mulai)
);

create table if not exists public.realisasi_sakti (
  id bigint generated by default as identity primary key,
  kua_id int not null references public.kua(id),
  pos_id int not null references public.pos(id),
  tahun int not null check (tahun between 2020 and 2100),
  bulan int not null check (bulan between 1 and 12),
  nominal bigint not null default 0 check (nominal >= 0),
  status_bayar text not null default 'BELUM_DIBAYAR' check (status_bayar in ('BELUM_DIBAYAR','SUDAH_DIBAYAR')),
  tanggal_bayar date,
  sumber text not null default 'SAKTI' check (sumber = 'SAKTI'),
  catatan text check (catatan is null or char_length(catatan) <= 500),
  created_by uuid references auth.users(id), created_at timestamptz not null default now(),
  updated_by uuid references auth.users(id), updated_at timestamptz not null default now(),
  unique (kua_id, pos_id, tahun, bulan),
  check (status_bayar = 'SUDAH_DIBAYAR' or (nominal = 0 and tanggal_bayar is null))
);
create index if not exists realisasi_sakti_filter on public.realisasi_sakti (tahun, bulan, kua_id);

create or replace function public.pos_sakti_ok(p_pos int) returns boolean
language sql stable set search_path = public as $$
  select exists (select 1 from pos where id = p_pos and kode_pos in ('522111','522112','522113'));
$$;

-- Metode yang berlaku untuk KUA + POS pada suatu bulan (belum ada konfigurasi = MANUAL)
create or replace function public.metode_pos(p_kua int, p_pos int, p_tahun int, p_bulan int) returns text
language sql stable set search_path = public as $$
  select coalesce((select metode from metode_pembayaran
                    where kua_id = p_kua and pos_id = p_pos and mulai <= make_date(p_tahun, p_bulan, 1)
                    order by mulai desc limit 1), 'MANUAL');
$$;

-- Realisasi SAKTI satu KUA pada satu bulan: {"<id POS>": nominal}. Belum dibayar bernominal 0, jadi tidak ikut.
create or replace function public.sakti_items(p_kua int, p_tahun int, p_bulan int) returns jsonb
language sql stable set search_path = public as $$
  select coalesce(jsonb_object_agg(pos_id::text, nominal), '{}'::jsonb) from realisasi_sakti
   where kua_id = p_kua and tahun = p_tahun and bulan = p_bulan and nominal > 0;
$$;

create or replace function public.sakti_year(p_kua int, p_pos int, p_tahun int) returns bigint
language sql stable set search_path = public as $$
  select coalesce(sum(nominal), 0)::bigint from realisasi_sakti where kua_id = p_kua and pos_id = p_pos and tahun = p_tahun;
$$;

-- Hanya admin. Versi baru tidak boleh bertabrakan dengan data yang sudah ada pada bulan-bulan yang metodenya berubah:
--   MANUAL -> SAKTI ditolak bila sudah ada Realisasi manual untuk POS itu; SAKTI -> MANUAL ditolak bila sudah ada Realisasi SAKTI.
create or replace function public.metode_guard() returns trigger
language plpgsql security definer set search_path = public as $$
declare lim date; bad text; ctx text; y int; yr int := extract(year from now() at time zone 'Asia/Jakarta')::int;
begin
  if not public.is_admin() then raise exception 'Hanya admin yang dapat mengubah metode pembayaran.'; end if;
  if new.kua_id is null or new.pos_id is null or new.mulai is null or new.metode is null then
    raise exception 'Data metode pembayaran tidak lengkap.'; end if;
  if tg_op = 'UPDATE' and (new.kua_id, new.pos_id, new.mulai) is distinct from (old.kua_id, old.pos_id, old.mulai) then
    raise exception 'KUA, POS, dan bulan berlaku tidak dapat diubah.'; end if;
  select nama_kua into ctx from kua where id = new.kua_id;
  if ctx is null then raise exception 'KUA tidak ditemukan.'; end if;
  if not pos_sakti_ok(new.pos_id) then
    raise exception 'Metode pembayaran hanya dapat diatur untuk Listrik (522111), Telepon/Internet (522112), dan Air (522113).'; end if;
  -- kunci yang sama dengan guard Realisasi (KUA + tahun) agar tidak berbalapan dengan operator
  for y in extract(year from new.mulai)::int .. greatest(extract(year from new.mulai)::int, yr) loop
    perform pg_advisory_xact_lock(new.kua_id, y);
  end loop;
  select min(mulai) into lim from metode_pembayaran where kua_id = new.kua_id and pos_id = new.pos_id and mulai > new.mulai;
  if new.metode = 'SAKTI' then
    select nama_bulan(r.bulan) || ' ' || r.tahun into bad from realisasi r
     where r.kua_id = new.kua_id and coalesce((r.items ->> new.pos_id::text)::bigint, 0) > 0
       and make_date(r.tahun, r.bulan, 1) >= new.mulai and (lim is null or make_date(r.tahun, r.bulan, 1) < lim)
     order by r.tahun, r.bulan limit 1;
    if bad is not null then
      raise exception '%: POS % sudah punya Realisasi manual pada %, jadi belum bisa SAKTI mulai % %. Pilih bulan berlaku sesudahnya.',
        ctx, pos_label(new.pos_id), bad, nama_bulan(extract(month from new.mulai)::int), extract(year from new.mulai)::int; end if;
  else
    select nama_bulan(s.bulan) || ' ' || s.tahun into bad from realisasi_sakti s
     where s.kua_id = new.kua_id and s.pos_id = new.pos_id and s.nominal > 0
       and make_date(s.tahun, s.bulan, 1) >= new.mulai and (lim is null or make_date(s.tahun, s.bulan, 1) < lim)
     order by s.tahun, s.bulan limit 1;
    if bad is not null then
      raise exception '%: POS % sudah punya Realisasi SAKTI pada %, jadi belum bisa MANUAL mulai % %. Pilih bulan berlaku sesudahnya.',
        ctx, pos_label(new.pos_id), bad, nama_bulan(extract(month from new.mulai)::int), extract(year from new.mulai)::int; end if;
  end if;
  if tg_op = 'INSERT' then new.created_by := auth.uid(); new.created_at := now();
  else new.created_by := old.created_by; new.created_at := old.created_at; end if;
  new.updated_by := auth.uid(); new.updated_at := now();
  return new;
end $$;
drop trigger if exists metode_guard on public.metode_pembayaran;
create trigger metode_guard before insert or update on public.metode_pembayaran
  for each row execute function public.metode_guard();

-- Hanya admin; POS harus bermetode SAKTI pada bulan itu; periode sudah berjalan (WIB); Belum dibayar = Rp 0; Sudah dibayar wajib bertanggal.
-- Jumlahnya ikut aturan yang sama dengan Realisasi manual: (manual + SAKTI) sebulan <= RPD bulan itu, dan POS setahun <= RPD POS itu setahun.
create or replace function public.realisasi_sakti_guard() returns trigger
language plpgsql security definer set search_path = public as $$
declare ctx text; rpd_m bigint; man_m bigint; sak_m bigint; cap bigint; used bigint;
        today date := (now() at time zone 'Asia/Jakarta')::date;
begin
  if not public.is_admin() then raise exception 'Realisasi SAKTI hanya dapat diinput oleh Admin.'; end if;
  if new.kua_id is null or new.pos_id is null then raise exception 'KUA dan POS wajib diisi.'; end if;
  if tg_op = 'UPDATE' and (new.kua_id, new.pos_id, new.tahun, new.bulan) is distinct from (old.kua_id, old.pos_id, old.tahun, old.bulan) then
    raise exception 'KUA, POS, tahun, dan bulan tidak dapat diubah. Input data baru untuk periode lain.'; end if;
  if new.tahun is null or new.bulan is null or new.tahun not between 2020 and 2100 or new.bulan not between 1 and 12 then
    raise exception 'Tahun atau bulan tidak valid.'; end if;
  select nama_kua into ctx from kua where id = new.kua_id;
  if ctx is null then raise exception 'KUA tidak ditemukan.'; end if;
  if not pos_sakti_ok(new.pos_id) then
    raise exception '%: POS % tidak dapat dibayar lewat SAKTI. Hanya Listrik, Telepon/Internet, dan Air.', ctx, coalesce(pos_label(new.pos_id), new.pos_id::text); end if;
  if coalesce(new.nominal, -1) < 0 then raise exception 'Nominal tidak boleh negatif.'; end if;
  if metode_pos(new.kua_id, new.pos_id, new.tahun, new.bulan) <> 'SAKTI' then
    raise exception '%: POS % bermetode MANUAL pada % %. Realisasi SAKTI hanya untuk POS bermetode SAKTI.',
      ctx, pos_label(new.pos_id), nama_bulan(new.bulan), new.tahun; end if;
  if make_date(new.tahun, new.bulan, 1) > date_trunc('month', now() at time zone 'Asia/Jakarta')::date then
    raise exception 'Realisasi SAKTI % % belum dapat diinput karena periodenya belum berjalan.', nama_bulan(new.bulan), new.tahun; end if;
  if coalesce(new.status_bayar, '') not in ('BELUM_DIBAYAR', 'SUDAH_DIBAYAR') then raise exception 'Status pembayaran tidak valid.'; end if;
  if new.status_bayar = 'BELUM_DIBAYAR' then
    if new.nominal <> 0 or new.tanggal_bayar is not null then
      raise exception 'Realisasi berstatus Belum dibayar harus bernominal Rp 0 dan tanpa tanggal pembayaran.'; end if;
  else
    if new.tanggal_bayar is null then raise exception 'Tanggal pembayaran wajib diisi untuk Realisasi yang sudah dibayar.'; end if;
    if new.tanggal_bayar > today then raise exception 'Tanggal pembayaran tidak boleh melebihi hari ini.'; end if;
  end if;
  new.catatan := nullif(btrim(coalesce(new.catatan, '')), '');

  perform pg_advisory_xact_lock(new.kua_id, new.tahun);
  if new.nominal > 0 and (tg_op = 'INSERT' or new.nominal is distinct from old.nominal) then
    select coalesce(sum(total), 0) into rpd_m from rpd where kua_id = new.kua_id and tahun = new.tahun and bulan = new.bulan;
    select coalesce(sum(total), 0) into man_m from realisasi where kua_id = new.kua_id and tahun = new.tahun and bulan = new.bulan;
    select coalesce(sum(nominal), 0) into sak_m from realisasi_sakti
     where kua_id = new.kua_id and tahun = new.tahun and bulan = new.bulan and pos_id <> new.pos_id;
    if man_m + sak_m + new.nominal > rpd_m then
      raise exception '%: total Realisasi % melebihi RPD bulan ini. Batas: %, Manual: %, SAKTI POS lain: %, dimasukkan: %, kelebihan: %.',
        ctx, nama_bulan(new.bulan), rp(rpd_m), rp(man_m), rp(sak_m), rp(new.nominal), rp(man_m + sak_m + new.nominal - rpd_m); end if;
    select coalesce(sum((items ->> new.pos_id::text)::bigint), 0) into cap from rpd where kua_id = new.kua_id and tahun = new.tahun;
    select coalesce(sum((items ->> new.pos_id::text)::bigint), 0) into used from realisasi where kua_id = new.kua_id and tahun = new.tahun;
    select used + coalesce(sum(nominal), 0) into used from realisasi_sakti
     where kua_id = new.kua_id and pos_id = new.pos_id and tahun = new.tahun and bulan <> new.bulan;
    if used + new.nominal > cap then
      raise exception '%: Realisasi POS % melebihi total RPD setahun. Batas: %, terpakai (bulan lain): %, dimasukkan: %, kelebihan: %.',
        ctx, pos_label(new.pos_id), rp(cap), rp(used), rp(new.nominal), rp(used + new.nominal - cap); end if;
  end if;
  if tg_op = 'INSERT' then new.created_by := auth.uid(); new.created_at := now();
  else new.created_by := old.created_by; new.created_at := old.created_at; end if;
  new.sumber := 'SAKTI'; new.updated_by := auth.uid(); new.updated_at := now();
  return new;
end $$;
drop trigger if exists realisasi_sakti_guard on public.realisasi_sakti;
create trigger realisasi_sakti_guard before insert or update on public.realisasi_sakti
  for each row execute function public.realisasi_sakti_guard();

-- RLS: admin membaca dan menulis semua; operator hanya MEMBACA milik KUA-nya. Tanpa policy DELETE.
alter table public.metode_pembayaran enable row level security;
drop policy if exists mp_read on public.metode_pembayaran;
create policy mp_read on public.metode_pembayaran for select to authenticated using (public.is_admin() or kua_id = public.my_kua());
drop policy if exists mp_ins on public.metode_pembayaran;
create policy mp_ins on public.metode_pembayaran for insert to authenticated with check (public.is_admin());
drop policy if exists mp_upd on public.metode_pembayaran;
create policy mp_upd on public.metode_pembayaran for update to authenticated using (public.is_admin()) with check (public.is_admin());

alter table public.realisasi_sakti enable row level security;
drop policy if exists rs_read on public.realisasi_sakti;
create policy rs_read on public.realisasi_sakti for select to authenticated using (public.is_admin() or kua_id = public.my_kua());
drop policy if exists rs_ins on public.realisasi_sakti;
create policy rs_ins on public.realisasi_sakti for insert to authenticated with check (public.is_admin());
drop policy if exists rs_upd on public.realisasi_sakti;
create policy rs_upd on public.realisasi_sakti for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- Lapisan tambahan di atas RLS: tanpa DELETE/TRUNCATE untuk klien, dan anon tidak punya akses sama sekali
revoke all on public.metode_pembayaran, public.realisasi_sakti from anon;
revoke delete, truncate on public.metode_pembayaran, public.realisasi_sakti from authenticated;

-- Migrasi SEKALI dari AutoPayment lama (nominal tetap) agar angka bulan-bulan yang sudah berjalan tidak berubah:
--   * tiap versi autopayment_pos menjadi metode SAKTI mulai bulan itu (dan MANUAL setelah versi ditutup);
--   * tiap bulan yang tercakup (sampai bulan berjalan) menjadi satu baris Realisasi SAKTI berstatus Sudah dibayar.
-- Sesudahnya bulan baru TIDAK terisi otomatis lagi: admin menginput realisasi SAKTI yang sebenarnya tiap bulan.
-- Penanda di config mencegah pengulangan (dan menyimpan ringkasan hasil). Tabel autopayment_pos dibiarkan sebagai arsip.
do $$
declare cur date := date_trunc('month', now() at time zone 'Asia/Jakarta')::date; n_ver int := 0; n_row int := 0; n_bentrok int := 0;
begin
  if exists (select 1 from public.config where key = 'sakti_migrasi_autopayment') then return; end if;
  if exists (select 1 from public.autopayment_pos where nominal > 0) then
    alter table public.metode_pembayaran disable trigger metode_guard;
    alter table public.realisasi_sakti disable trigger realisasi_sakti_guard;

    insert into public.metode_pembayaran (kua_id, pos_id, metode, mulai)
    select kua_id, pos_id, case when bool_or(m = 'SAKTI') then 'SAKTI' else 'MANUAL' end, bln
      from (select kua_id, pos_id, mulai as bln, 'SAKTI' as m from public.autopayment_pos where nominal > 0
            union all
            select kua_id, pos_id, (sampai + interval '1 month')::date, 'MANUAL' from public.autopayment_pos
             where nominal > 0 and sampai is not null) e
     group by kua_id, pos_id, bln
    on conflict (kua_id, pos_id, mulai) do nothing;
    get diagnostics n_ver = row_count;

    insert into public.realisasi_sakti (kua_id, pos_id, tahun, bulan, nominal, status_bayar, catatan)
    select a.kua_id, a.pos_id, extract(year from (a.mulai + make_interval(months => g)))::int,
           extract(month from (a.mulai + make_interval(months => g)))::int, a.nominal, 'SUDAH_DIBAYAR',
           'Migrasi dari AutoPayment (nominal tetap)'
      from public.autopayment_pos a
     cross join lateral generate_series(0, ((extract(year from least(coalesce(a.sampai, cur), cur)) - extract(year from a.mulai)) * 12
            + extract(month from least(coalesce(a.sampai, cur), cur)) - extract(month from a.mulai))::int) g
     where a.nominal > 0 and a.mulai <= cur
    on conflict (kua_id, pos_id, tahun, bulan) do nothing;
    get diagnostics n_row = row_count;

    alter table public.metode_pembayaran enable trigger metode_guard;
    alter table public.realisasi_sakti enable trigger realisasi_sakti_guard;

    -- bulan yang sudah punya Realisasi manual DAN SAKTI untuk POS yang sama (warisan aturan lama): hanya dilaporkan, tidak diubah
    select count(*) into n_bentrok from public.realisasi r
      cross join lateral jsonb_each(r.items) i
      join public.realisasi_sakti s on s.kua_id = r.kua_id and s.tahun = r.tahun and s.bulan = r.bulan and s.pos_id::text = i.key
     where s.nominal > 0 and (i.value #>> '{}')::bigint > 0;
  end if;
  insert into public.config (key, value)
  values ('sakti_migrasi_autopayment', jsonb_build_object('waktu', now(), 'versi_metode', n_ver, 'baris_realisasi_sakti', n_row, 'bentrok_dengan_manual', n_bentrok))
  on conflict (key) do nothing;
  raise notice 'Migrasi AutoPayment -> SAKTI: % versi metode, % baris Realisasi SAKTI, % bulan bentrok dengan Realisasi manual.', n_ver, n_row, n_bentrok;
end $$;

-- 10) SALIN DATA LAMA (hanya bila tabel lama ada dan tabel baru masih kosong) --------------------------
-- Baris AutoPayment lama tidak disalin: kini dihitung dari tabel autopayment_pos.
do $$ begin
  if to_regclass('public.rpd_lama') is not null and not exists (select 1 from public.rpd) then
    insert into public.rpd (kua_id, tahun, bulan, items, total, updated_by, updated_at)
    select kua_id, tahun, bulan,
           coalesce(jsonb_object_agg(pos_id::text, nominal) filter (where nominal > 0), '{}'::jsonb),
           sum(nominal), (array_agg(updated_by))[1], max(updated_at)
      from public.rpd_lama group by kua_id, tahun, bulan;
  end if;
  if to_regclass('public.realisasi_lama') is not null and not exists (select 1 from public.realisasi) then
    insert into public.realisasi (kua_id, tahun, bulan, items, total, status, file_lpj_url, catatan_admin,
                                  submitted_by, submitted_at, verified_by, verified_at, paid_at)
    select kua_id, tahun, bulan,
           coalesce(jsonb_object_agg(pos_id::text, nominal) filter (where nominal > 0), '{}'::jsonb), sum(nominal),
           case when bool_or(status = 'rejected') then 'rejected' when bool_or(status = 'waiting') then 'waiting'
                when bool_or(status = 'approved') then 'approved' else 'paid' end,
           max(file_lpj_url), max(catatan_admin), (array_agg(submitted_by))[1], max(submitted_at),
           (array_agg(verified_by))[1], max(verified_at), max(paid_at)
      from public.realisasi_lama where not is_autopayment group by kua_id, tahun, bulan;
  end if;
end $$;

-- 11) PEMBERSIHAN: penerbitan otomatis lama (tidak dipakai lagi) dan tabel lama ---------------------------
do $$ begin perform cron.unschedule('autopayment-harian'); exception when others then null; end $$;
drop function if exists public.generate_autopayment(int, int);
drop function if exists public.realisasi_month_lock();

-- Hapus rpd_lama / realisasi_lama. Pengaman: dibatalkan bila ada bulan lama yang belum punya record baru.
do $$
declare hilang int;
begin
  if to_regclass('public.rpd_lama') is not null then
    select count(*) into hilang from (select distinct kua_id, tahun, bulan from public.rpd_lama) l
     where not exists (select 1 from public.rpd n where n.kua_id = l.kua_id and n.tahun = l.tahun and n.bulan = l.bulan);
    if hilang > 0 then
      raise exception 'Dibatalkan: % bulan RPD lama belum ada di tabel baru. Jalankan migration-07 lebih dulu.', hilang;
    end if;
  end if;
  if to_regclass('public.realisasi_lama') is not null then
    select count(*) into hilang from (select distinct kua_id, tahun, bulan from public.realisasi_lama where not is_autopayment) l
     where not exists (select 1 from public.realisasi n where n.kua_id = l.kua_id and n.tahun = l.tahun and n.bulan = l.bulan);
    if hilang > 0 then
      raise exception 'Dibatalkan: % bulan Realisasi lama belum ada di tabel baru. Jalankan migration-07 lebih dulu.', hilang;
    end if;
  end if;
end $$;

drop table if exists public.rpd_lama;
drop table if exists public.realisasi_lama;