-- =====================================================================================
-- BOP KUA Kabupaten Indramayu: SKEMA DATABASE LENGKAP (satu file)
--
-- Cara pakai: Supabase > SQL Editor > New query > tempel seluruh isi file ini > Run.
-- Aman dijalankan berulang (idempotent). Cocok untuk:
--   (a) pemasangan baru (database kosong);
--   (b) database versi lama: RPD/Realisasi per-POS dikonversi otomatis menjadi 1 record per bulan (JSON),
--       lalu tabel lama (rpd_lama, realisasi_lama) dihapus setelah dipastikan datanya sudah pindah.
--
-- Isi: 0 Persiapan | 1 Profil dan hak akses | 2 KUA | 3 Fungsi bantu | 4 POS | 5 Config | 6 Anggaran |
--      7 AutoPayment | 8 RPD | 9 Realisasi | 10 Salin data lama | 11 Pembersihan | 12 Jaspro Transport
--
-- Model data: RPD dan Realisasi = 1 record per KUA per bulan; rincian POS disimpan di kolom JSON
--   items = {"<id POS>": nominal, ...}. Total dihitung otomatis oleh trigger. AutoPayment tidak disimpan per bulan:
--   dihitung dari tabel autopayment_pos (nominal tetap + rentang bulan berlaku), jadi tanpa cron dan tanpa log.
-- Keamanan: RLS membatasi operator ke KUA-nya; trigger SECURITY DEFINER menegakkan semua aturan di sisi server.
-- =====================================================================================

-- 0) PERSIAPAN: bila masih struktur lama (RPD/Realisasi per-POS), pindahkan dulu menjadi *_lama
do $$ begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'rpd' and column_name = 'pos_id') then
    drop trigger if exists rpd_guard on public.rpd;
    alter table public.rpd rename to rpd_lama;
  end if;
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'realisasi' and column_name = 'pos_id') then
    drop trigger if exists realisasi_a_lock on public.realisasi;
    drop trigger if exists realisasi_guard on public.realisasi;
    alter table public.realisasi rename to realisasi_lama;
  end if;
end $$;

-- 1) PROFIL AKUN DAN HAK AKSES -----------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nama text not null,
  kua text,
  role text not null default 'operator' check (role in ('admin','operator')),
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

create or replace function public.is_admin() returns boolean
language sql security definer stable set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

-- operator hanya melihat profilnya sendiri, admin melihat semua. Tanpa policy insert/update/delete: klien tidak bisa mengubah role.
drop policy if exists "baca profil sendiri atau admin" on public.profiles;
create policy "baca profil sendiri atau admin" on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.is_admin());

-- profil dibuat otomatis saat akun dibuat (data dari user_metadata); kua_id dicari dari nama KUA
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, nama, kua, kua_id, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'nama', new.email), new.raw_user_meta_data->>'kua',
    (select id from public.kua where nama_kua = new.raw_user_meta_data->>'kua'),
    case when new.raw_user_meta_data->>'role' = 'admin' then 'admin' else 'operator' end);
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- 2) KUA (31 kecamatan) ------------------------------------------------------------------
create table if not exists public.kua (
  id int generated by default as identity primary key,
  nama_kua text not null unique,
  kecamatan text not null,
  status text not null default 'aktif' check (status in ('aktif','nonaktif'))
);
insert into public.kua (nama_kua, kecamatan)
select 'KUA Kec. ' || k, k from unnest(array['Anjatan','Arahan','Balongan','Bangodua','Bongas','Cantigi','Cikedung',
  'Gabuswetan','Gantar','Haurgeulis','Indramayu','Jatibarang','Juntinyuat','Kandanghaur','Karangampel','Kedokan Bunder',
  'Kertasemaya','Krangkeng','Kroya','Lelea','Lohbener','Losarang','Pasekan','Patrol','Sindang','Sliyeg','Sukagumiwang',
  'Sukra','Terisi','Tukdana','Widasari']) as k
on conflict (nama_kua) do nothing;
alter table public.profiles add column if not exists kua_id int references public.kua(id);
update public.profiles p set kua_id = k.id from public.kua k where p.kua_id is null and p.kua = k.nama_kua;

create or replace function public.my_kua() returns int
language sql security definer stable set search_path = public as $$
  select kua_id from public.profiles where id = auth.uid();
$$;

alter table public.kua enable row level security;
drop policy if exists kua_read on public.kua;
create policy kua_read on public.kua for select to authenticated using (true);

-- 3) FUNGSI BANTU ------------------------------------------------------------------------
create or replace function public.rp(n bigint) returns text
language sql stable as $$ select 'Rp ' || replace(to_char(n, 'FM999,999,999,999,999'), ',', '.'); $$;

create or replace function public.nama_bulan(m int) returns text language sql immutable as $$
  select (array['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'])[m];
$$;

create or replace function public.items_total(p jsonb) returns bigint
language sql immutable as $$ select coalesce(sum(value::bigint), 0)::bigint from jsonb_each_text(p); $$;

-- 4) POS: satu baris = satu unit input (rincian, atau kode POS itu sendiri bila tanpa rincian) -------------
create table if not exists public.pos (
  id int generated by default as identity primary key,
  kode_pos text not null,
  nama_pos text not null,
  nama_rincian text,
  urutan int not null unique
);
insert into public.pos (kode_pos, nama_pos, nama_rincian, urutan) values
 ('521111','Belanja Operasional Perkantoran','ATK Kantor',1),
 ('521111','Belanja Operasional Perkantoran','Jamuan Tamu',2),
 ('521111','Belanja Operasional Perkantoran','Pramubakti',3),
 ('521111','Belanja Operasional Perkantoran','Alat Rumah Tangga Kantor',4),
 ('521211','Belanja Bahan','Penggandaan / Penjilidan',5),
 ('521211','Belanja Bahan','Spanduk',6),
 ('522111','Belanja Langganan Listrik',null,7),
 ('522112','Belanja Langganan Telepon / Internet',null,8),
 ('522113','Belanja Langganan Air',null,9),
 ('523111','Belanja Pemeliharaan Gedung dan Bangunan',null,10),
 ('523121','Belanja Pemeliharaan Peralatan dan Mesin',null,11)
on conflict (urutan) do nothing;

create or replace function public.pos_label(p_id int) returns text
language sql stable set search_path = public as $$
  select kode_pos || ' ' || coalesce(nama_rincian, nama_pos) from pos where id = p_id;
$$;

-- Rapikan dan validasi rincian: kunci = id POS yang ada, nilai = bilangan bulat >= 0; nilai 0 dibuang
create or replace function public.norm_items(p jsonb) returns jsonb
language plpgsql stable set search_path = public as $$
declare k text; v jsonb; r jsonb := '{}'::jsonb;
begin
  if p is null or jsonb_typeof(p) <> 'object' then raise exception 'Format rincian POS tidak valid.'; end if;
  for k, v in select key, value from jsonb_each(p) loop
    if jsonb_typeof(v) <> 'number' or (v #>> '{}') !~ '^[0-9]+$' then
      raise exception 'Nominal POS % harus bilangan bulat dan tidak negatif.', k; end if;
    if not exists (select 1 from pos where id::text = k) then raise exception 'POS % tidak dikenal.', k; end if;
    if (v #>> '{}')::bigint > 0 then r := r || jsonb_build_object(k, (v #>> '{}')::bigint); end if;
  end loop;
  return r;
end $$;

alter table public.pos enable row level security;
drop policy if exists pos_read on public.pos;
create policy pos_read on public.pos for select to authenticated using (true);

-- 5) CONFIG global ---------------------------------------------------------------------------
create table if not exists public.config (
  key text primary key, value jsonb not null,
  updated_by uuid references auth.users(id), updated_at timestamptz not null default now()
);
insert into public.config (key, value) values
 ('wajib_lpj','true'),('rpd_enabled','true'),('realisasi_enabled','true'),
 ('max_file_size_mb','5'),('max_file_count','3'),('bulan_edit_rpd','[1,2,3,4,5,6,7,8,9,10,11,12]')
on conflict (key) do nothing;

-- Operator boleh edit RPD hanya jika rpd_enabled dan bulan ada di bulan_edit_rpd
create or replace function public.rpd_open(m int) returns boolean
language sql security definer stable set search_path = public as $$
  select coalesce((select (value #>> '{}')::boolean from config where key = 'rpd_enabled'), false)
     and exists (select 1 from config where key = 'bulan_edit_rpd' and value @> to_jsonb(m));
$$;

alter table public.config enable row level security;
drop policy if exists cfg_read on public.config;
create policy cfg_read on public.config for select to authenticated using (true);
drop policy if exists cfg_admin on public.config;
create policy cfg_admin on public.config for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- 6) ANGGARAN TAHUNAN ------------------------------------------------------------------------
create table if not exists public.anggaran (
  id bigint generated by default as identity primary key,
  kua_id int not null references public.kua(id),
  tahun int not null check (tahun between 2020 and 2100),
  nominal_total bigint not null check (nominal_total >= 0),
  updated_by uuid references auth.users(id), updated_at timestamptz not null default now(),
  unique (kua_id, tahun)
);

-- Anggaran tidak boleh diturunkan di bawah total RPD yang sudah diisi (pesan menyebut nama KUA)
create or replace function public.anggaran_guard() returns trigger
language plpgsql security definer set search_path = public as $$
declare used bigint;
begin
  perform pg_advisory_xact_lock(new.kua_id, new.tahun);
  select coalesce(sum(total), 0) into used from rpd where kua_id = new.kua_id and tahun = new.tahun;
  if new.nominal_total < used then
    raise exception '%: Anggaran % lebih kecil dari total RPD yang sudah diisi (%). Kurangi RPD lebih dulu.',
      (select nama_kua from kua where id = new.kua_id), rp(new.nominal_total), rp(used);
  end if;
  new.updated_by := auth.uid(); new.updated_at := now();
  return new;
end $$;
drop trigger if exists anggaran_guard on public.anggaran;
create trigger anggaran_guard before insert or update on public.anggaran
  for each row execute function public.anggaran_guard();

alter table public.anggaran enable row level security;
drop policy if exists ang_read on public.anggaran;
create policy ang_read on public.anggaran for select to authenticated using (public.is_admin() or kua_id = public.my_kua());
drop policy if exists ang_admin on public.anggaran;
create policy ang_admin on public.anggaran for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- 7) AUTOPAYMENT (nominal tetap per bulan; hanya Listrik 522111, Telepon/Internet 522112, Air 522113) -----------
-- Versi konfigurasi: (mulai, sampai) agar riwayat bulan lampau tidak berubah ketika nominal diganti.
create table if not exists public.autopayment_pos (
  kua_id int not null references public.kua(id) on delete cascade,
  pos_id int not null references public.pos(id) on delete cascade,
  nominal bigint not null default 0 check (nominal >= 0),
  mulai date not null default date_trunc('month', now() at time zone 'Asia/Jakarta')::date,
  sampai date,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  primary key (kua_id, pos_id, mulai)
);
-- (database lama: lengkapi kolom dan kunci utama)
alter table public.autopayment_pos add column if not exists nominal bigint not null default 0 check (nominal >= 0);
alter table public.autopayment_pos add column if not exists mulai date not null default date_trunc('month', now() at time zone 'Asia/Jakarta')::date;
alter table public.autopayment_pos add column if not exists sampai date;
do $$ begin
  if (select array_length(conkey, 1) from pg_constraint where conrelid = 'public.autopayment_pos'::regclass and contype = 'p') = 2 then
    alter table public.autopayment_pos drop constraint autopayment_pos_pkey;
    alter table public.autopayment_pos add primary key (kua_id, pos_id, mulai);
  end if;
end $$;

create or replace function public.autopayment_pos_guard() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from pos where id = new.pos_id and kode_pos in ('522111','522112','522113')) then
    raise exception 'AutoPayment hanya untuk Listrik, Telepon/Internet, dan Air.'; end if;
  return new;
end $$;
drop trigger if exists autopayment_pos_guard on public.autopayment_pos;
create trigger autopayment_pos_guard before insert or update on public.autopayment_pos
  for each row execute function public.autopayment_pos_guard();

-- AutoPayment virtual: nominal tetap selama versi konfigurasi berlaku, sampai bulan berjalan (WIB)
create or replace function public.auto_items(p_kua int, p_tahun int, p_bulan int) returns jsonb
language sql stable set search_path = public as $$
  select coalesce(jsonb_object_agg(pos_id::text, nominal), '{}'::jsonb) from autopayment_pos
   where kua_id = p_kua and nominal > 0
     and make_date(p_tahun, p_bulan, 1) <= date_trunc('month', now() at time zone 'Asia/Jakarta')::date
     and make_date(p_tahun, p_bulan, 1) >= mulai
     and (sampai is null or make_date(p_tahun, p_bulan, 1) <= sampai);
$$;

create or replace function public.auto_year(p_kua int, p_pos int, p_tahun int) returns bigint
language sql stable set search_path = public as $$
  select coalesce(sum(a.nominal), 0)::bigint from autopayment_pos a, generate_series(1, 12) m
   where a.kua_id = p_kua and a.pos_id = p_pos and a.nominal > 0
     and make_date(p_tahun, m, 1) <= date_trunc('month', now() at time zone 'Asia/Jakarta')::date
     and make_date(p_tahun, m, 1) >= a.mulai and (a.sampai is null or make_date(p_tahun, m, 1) <= a.sampai);
$$;

-- Atur AutoPayment sekaligus: [{"kua_id":1,"pos_id":7,"nominal":300000}, ...]; nominal 0 = nonaktifkan. Berlaku mulai bulan ini.
create or replace function public.set_autopayment(p_items jsonb) returns void
language plpgsql security definer set search_path = public as $$
declare it jsonb; a record; n bigint; cur date := date_trunc('month', now() at time zone 'Asia/Jakarta')::date;
begin
  if not public.is_admin() then raise exception 'Hanya admin yang dapat mengatur AutoPayment.'; end if;
  for it in select value from jsonb_array_elements(p_items) loop
    n := coalesce((it ->> 'nominal')::bigint, 0);
    select * into a from autopayment_pos where kua_id = (it ->> 'kua_id')::int and pos_id = (it ->> 'pos_id')::int and sampai is null;
    if n > 0 then
      if found then
        if a.nominal = n then continue; end if;
        if a.mulai >= cur then
          update autopayment_pos set nominal = n where kua_id = a.kua_id and pos_id = a.pos_id and mulai = a.mulai;
        else
          update autopayment_pos set sampai = (cur - interval '1 month')::date where kua_id = a.kua_id and pos_id = a.pos_id and mulai = a.mulai;
          insert into autopayment_pos (kua_id, pos_id, nominal, mulai) values (a.kua_id, a.pos_id, n, cur);
        end if;
      else
        insert into autopayment_pos (kua_id, pos_id, nominal, mulai) values ((it ->> 'kua_id')::int, (it ->> 'pos_id')::int, n, cur);
      end if;
    elsif found then
      if a.mulai >= cur then
        delete from autopayment_pos where kua_id = a.kua_id and pos_id = a.pos_id and mulai = a.mulai;
      else
        update autopayment_pos set sampai = (cur - interval '1 month')::date where kua_id = a.kua_id and pos_id = a.pos_id and mulai = a.mulai;
      end if;
    end if;
  end loop;
end $$;
revoke execute on function public.set_autopayment(jsonb) from public, anon;
grant execute on function public.set_autopayment(jsonb) to authenticated;

alter table public.autopayment_pos enable row level security;
drop policy if exists ap_admin on public.autopayment_pos;
create policy ap_admin on public.autopayment_pos for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
drop policy if exists ap_read on public.autopayment_pos;
create policy ap_read on public.autopayment_pos for select to authenticated using (kua_id = public.my_kua());

-- 8) RPD: 1 record = 1 KUA x 1 bulan -----------------------------------------------------------
create table if not exists public.rpd (
  id bigint generated by default as identity primary key,
  kua_id int not null references public.kua(id),
  tahun int not null check (tahun between 2020 and 2100),
  bulan int not null check (bulan between 1 and 12),
  items jsonb not null default '{}'::jsonb check (jsonb_typeof(items) = 'object'),
  total bigint not null default 0 check (total >= 0),
  updated_by uuid references auth.users(id), updated_at timestamptz not null default now(),
  unique (kua_id, tahun, bulan)
);

-- Total RPD setahun <= Anggaran Tahunan; operator hanya boleh menyentuh KUA-nya sendiri
create or replace function public.rpd_guard() returns trigger
language plpgsql security definer set search_path = public as $$
declare cap bigint; used bigint;
begin
  if not public.is_admin() and public.my_kua() is distinct from new.kua_id then
    raise exception 'Anda tidak berhak mengubah data KUA lain.'; end if;
  new.items := norm_items(new.items); new.total := items_total(new.items);
  perform pg_advisory_xact_lock(new.kua_id, new.tahun);
  select nominal_total into cap from anggaran where kua_id = new.kua_id and tahun = new.tahun;
  if cap is null then raise exception 'Anggaran Tahunan % belum ditetapkan admin untuk KUA ini.', new.tahun; end if;
  select coalesce(sum(total), 0) into used from rpd where kua_id = new.kua_id and tahun = new.tahun and bulan <> new.bulan;
  if used + new.total > cap then
    raise exception 'Total RPD melebihi Anggaran Tahunan. Batas: %, sudah terpakai (bulan lain): %, dimasukkan: %, kelebihan: %.',
      rp(cap), rp(used), rp(new.total), rp(used + new.total - cap);
  end if;
  new.updated_by := auth.uid(); new.updated_at := now();
  return new;
end $$;
drop trigger if exists rpd_guard on public.rpd;
create trigger rpd_guard before insert or update on public.rpd for each row execute function public.rpd_guard();

alter table public.rpd enable row level security;
drop policy if exists rpd_read on public.rpd;
create policy rpd_read on public.rpd for select to authenticated using (public.is_admin() or kua_id = public.my_kua());
drop policy if exists rpd_write on public.rpd;
create policy rpd_write on public.rpd for all to authenticated
  using (public.is_admin() or (kua_id = public.my_kua() and public.rpd_open(bulan)))
  with check (public.is_admin() or (kua_id = public.my_kua() and public.rpd_open(bulan)));

-- 9) REALISASI: 1 record = 1 KUA x 1 bulan ------------------------------------------------------
create table if not exists public.realisasi (
  id bigint generated by default as identity primary key,
  kua_id int not null references public.kua(id),
  tahun int not null check (tahun between 2020 and 2100),
  bulan int not null check (bulan between 1 and 12),
  items jsonb not null default '{}'::jsonb check (jsonb_typeof(items) = 'object'),
  total bigint not null default 0 check (total >= 0),
  status text not null default 'waiting' check (status in ('waiting','approved','rejected','paid')),
  file_lpj_url text check (file_lpj_url is null or file_lpj_url ~ '^https://(drive|docs)\.google\.com/'),
  catatan_admin text,
  submitted_by uuid references auth.users(id), submitted_at timestamptz,
  verified_by uuid references auth.users(id), verified_at timestamptz,
  paid_at timestamptz,
  unique (kua_id, tahun, bulan)
);
create index if not exists realisasi_filter on public.realisasi (tahun, status, kua_id);

-- Operator: hanya boleh membuat (belum ada) atau memperbaiki yang berstatus rejected; setelah dikirim jadi waiting dan terkunci.
-- Admin: boleh mengubah status apa pun kapan pun, tetapi TIDAK boleh mengubah nominal / dokumen LPJ.
create or replace function public.realisasi_guard() returns trigger
language plpgsql security definer set search_path = public as $$
declare au jsonb; rpd_m bigint; au_m bigint; ctx text; k text; v bigint; cap bigint; used bigint;
begin
  if tg_op = 'UPDATE' and public.is_admin() then
    if (new.kua_id, new.tahun, new.bulan, new.items, new.total, new.file_lpj_url)
       is distinct from (old.kua_id, old.tahun, old.bulan, old.items, old.total, old.file_lpj_url) then
      raise exception 'Admin hanya dapat mengubah status dan catatan, bukan nominal atau dokumen LPJ.'; end if;
    if new.status = 'rejected' and btrim(coalesce(new.catatan_admin, '')) = '' then
      raise exception 'Alasan penolakan wajib diisi.'; end if;
    if new.status <> old.status then
      new.verified_by := auth.uid(); new.verified_at := now();
      new.paid_at := case when new.status = 'paid' then now() end;
    end if;
    return new;
  end if;

  if public.my_kua() is distinct from new.kua_id then
    raise exception 'Anda tidak berhak mengubah data KUA lain.'; end if;
  if tg_op = 'UPDATE' then
    if old.status <> 'rejected' then
      raise exception 'Realisasi berstatus % tidak dapat diubah. Hanya Realisasi yang ditolak yang dapat diperbaiki.',
        case old.status when 'waiting' then 'Menunggu verifikasi' when 'approved' then 'Disetujui' else 'Dibayar' end; end if;
    if (new.kua_id, new.tahun, new.bulan) is distinct from (old.kua_id, old.tahun, old.bulan) then
      raise exception 'KUA, tahun, dan bulan tidak dapat diubah.'; end if;
    new.catatan_admin := old.catatan_admin; new.verified_by := old.verified_by; new.verified_at := old.verified_at;
  else
    new.catatan_admin := null; new.verified_by := null; new.verified_at := null;
  end if;
  new.paid_at := null; new.status := 'waiting'; new.submitted_by := auth.uid(); new.submitted_at := now();
  new.items := norm_items(new.items); new.total := items_total(new.items);

  if coalesce((select (value #>> '{}')::boolean from config where key = 'realisasi_enabled'), false) is not true then
    raise exception 'Pengisian Realisasi sedang ditutup oleh admin.'; end if;
  if (now() at time zone 'Asia/Jakarta')::date < make_date(new.tahun, new.bulan, 10) then
    raise exception 'Realisasi % % baru dapat disubmit mulai tanggal 10 %.', nama_bulan(new.bulan), new.tahun, nama_bulan(new.bulan); end if;
  if new.total > 0 and new.file_lpj_url is null then
    raise exception 'LPJ wajib dilampirkan (unggah file LPJ).'; end if;

  select nama_kua into ctx from kua where id = new.kua_id;
  perform pg_advisory_xact_lock(new.kua_id, new.tahun);
  au := auto_items(new.kua_id, new.tahun, new.bulan);
  for k in select jsonb_object_keys(new.items) loop
    if jsonb_exists(au, k) then
      raise exception '%: POS % dibayar otomatis pada bulan ini dan tidak dapat diisi manual.', ctx, pos_label(k::int); end if;
  end loop;

  select coalesce(sum(total), 0) into rpd_m from rpd where kua_id = new.kua_id and tahun = new.tahun and bulan = new.bulan;
  au_m := items_total(au);
  if new.total + au_m > rpd_m then
    raise exception '%: total Realisasi bulan ini melebihi RPD bulan ini. Batas: %, AutoPayment: %, dimasukkan: %, kelebihan: %.',
      ctx, rp(rpd_m), rp(au_m), rp(new.total), rp(new.total + au_m - rpd_m); end if;

  for k, v in select key, value::bigint from jsonb_each_text(new.items) loop
    select coalesce(sum((items ->> k)::bigint), 0) into cap from rpd where kua_id = new.kua_id and tahun = new.tahun;
    select coalesce(sum((items ->> k)::bigint), 0) + auto_year(new.kua_id, k::int, new.tahun) into used
      from realisasi where kua_id = new.kua_id and tahun = new.tahun and bulan <> new.bulan;
    if used + v > cap then
      raise exception '%: Realisasi POS % melebihi total RPD setahun. Batas: %, terpakai (bulan lain + AutoPayment): %, dimasukkan: %, kelebihan: %.',
        ctx, pos_label(k::int), rp(cap), rp(used), rp(v), rp(used + v - cap); end if;
  end loop;
  return new;
end $$;
drop trigger if exists realisasi_guard on public.realisasi;
create trigger realisasi_guard before insert or update on public.realisasi
  for each row execute function public.realisasi_guard();

-- aturan status dijaga trigger realisasi_guard agar pesan errornya jelas
alter table public.realisasi enable row level security;
drop policy if exists rl_read on public.realisasi;
create policy rl_read on public.realisasi for select to authenticated using (public.is_admin() or kua_id = public.my_kua());
drop policy if exists rl_ins on public.realisasi;
create policy rl_ins on public.realisasi for insert to authenticated with check (kua_id = public.my_kua());
drop policy if exists rl_upd on public.realisasi;
create policy rl_upd on public.realisasi for update to authenticated
  using (public.is_admin() or kua_id = public.my_kua())
  with check (public.is_admin() or kua_id = public.my_kua());

-- 10) SALIN DATA LAMA (hanya bila tabel lama ada dan tabel baru masih kosong) --------------------------
-- Baris AutoPayment lama tidak disalin: kini dihitung dari tabel autopayment_pos.
do $$ begin
  if to_regclass('public.rpd_lama') is not null and not exists (select 1 from public.rpd) then
    insert into public.rpd (kua_id, tahun, bulan, items, total, updated_by, updated_at)
    select kua_id, tahun, bulan,
           coalesce(jsonb_object_agg(pos_id::text, nominal) filter (where nominal > 0), '{}'::jsonb),
           sum(nominal), (array_agg(updated_by))[1], max(updated_at)
      from public.rpd_lama group by kua_id, tahun, bulan;
  end if;
  if to_regclass('public.realisasi_lama') is not null and not exists (select 1 from public.realisasi) then
    insert into public.realisasi (kua_id, tahun, bulan, items, total, status, file_lpj_url, catatan_admin,
                                  submitted_by, submitted_at, verified_by, verified_at, paid_at)
    select kua_id, tahun, bulan,
           coalesce(jsonb_object_agg(pos_id::text, nominal) filter (where nominal > 0), '{}'::jsonb), sum(nominal),
           case when bool_or(status = 'rejected') then 'rejected' when bool_or(status = 'waiting') then 'waiting'
                when bool_or(status = 'approved') then 'approved' else 'paid' end,
           max(file_lpj_url), max(catatan_admin), (array_agg(submitted_by))[1], max(submitted_at),
           (array_agg(verified_by))[1], max(verified_at), max(paid_at)
      from public.realisasi_lama where not is_autopayment group by kua_id, tahun, bulan;
  end if;
end $$;

-- 11) PEMBERSIHAN: penerbitan otomatis lama (tidak dipakai lagi) dan tabel lama ---------------------------
do $$ begin perform cron.unschedule('autopayment-harian'); exception when others then null; end $$;
drop function if exists public.generate_autopayment(int, int);
drop function if exists public.realisasi_month_lock();

-- Hapus rpd_lama / realisasi_lama. Pengaman: dibatalkan bila ada bulan lama yang belum punya record baru.
do $$
declare hilang int;
begin
  if to_regclass('public.rpd_lama') is not null then
    select count(*) into hilang from (select distinct kua_id, tahun, bulan from public.rpd_lama) l
     where not exists (select 1 from public.rpd n where n.kua_id = l.kua_id and n.tahun = l.tahun and n.bulan = l.bulan);
    if hilang > 0 then
      raise exception 'Dibatalkan: % bulan RPD lama belum ada di tabel baru. Jalankan migration-07 lebih dulu.', hilang;
    end if;
  end if;
  if to_regclass('public.realisasi_lama') is not null then
    select count(*) into hilang from (select distinct kua_id, tahun, bulan from public.realisasi_lama where not is_autopayment) l
     where not exists (select 1 from public.realisasi n where n.kua_id = l.kua_id and n.tahun = l.tahun and n.bulan = l.bulan);
    if hilang > 0 then
      raise exception 'Dibatalkan: % bulan Realisasi lama belum ada di tabel baru. Jalankan migration-07 lebih dulu.', hilang;
    end if;
  end if;
end $$;

drop table if exists public.rpd_lama;
drop table if exists public.realisasi_lama;

-- 12) JASPRO TRANSPORT (alat sekali pakai: Laporan Nominatif PNBP NR) ---------------------------------------
-- Hemat kuota: HANYA SATU baris (id = 1). Setiap simpan menimpa kolom yang dikirim; tanpa riwayat, log, atau tabel per bulan.
-- master = Master Rekening [{id,nama,namaPemilik,noRekening}] | laporan = {fileName, rows:[...]} terakhir (null = belum ada)
-- settings = periode, tarif, PPh, blok tanda tangan. Hanya admin yang boleh membaca dan menulis (RLS).
create table if not exists public.jaspro_data (
  id         int primary key default 1 check (id = 1),
  master     jsonb not null default '[]'::jsonb,
  laporan    jsonb,
  settings   jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);
create or replace function public.jaspro_guard() returns trigger
language plpgsql set search_path = public as $$
begin
  if jsonb_typeof(new.master) is distinct from 'array' then raise exception 'Master Rekening harus berupa daftar.'; end if;
  if jsonb_array_length(new.master) > 2000 then raise exception 'Master Rekening maksimal 2000 data.'; end if;
  if new.laporan is not null then
    if jsonb_typeof(new.laporan) is distinct from 'object' or jsonb_typeof(new.laporan->'rows') is distinct from 'array' then
      raise exception 'Laporan Nominatif tidak valid.'; end if;
    if jsonb_array_length(new.laporan->'rows') > 5000 then raise exception 'Laporan Nominatif maksimal 5000 baris.'; end if;
  end if;
  if jsonb_typeof(new.settings) is distinct from 'object' then raise exception 'Pengaturan Jaspro tidak valid.'; end if;
  new.updated_by := auth.uid(); new.updated_at := now();
  return new;
end $$;
drop trigger if exists jaspro_guard on public.jaspro_data;
create trigger jaspro_guard before insert or update on public.jaspro_data for each row execute function public.jaspro_guard();

alter table public.jaspro_data enable row level security;
drop policy if exists jaspro_admin on public.jaspro_data;
create policy jaspro_admin on public.jaspro_data for all to authenticated using (public.is_admin()) with check (public.is_admin());
revoke all on public.jaspro_data from anon;
grant select, insert, update on public.jaspro_data to authenticated;
insert into public.jaspro_data (id) values (1) on conflict (id) do nothing;